### ISSUE TITLE
http://stopwritingramblingcommitmessages.com/

### ISSUE THREAD

**Issue by paultag** [fiendish/aardwolfclientpackage#198]
http://stopwritingramblingcommitmessages.com/

**Comment by fiendish** [comment]
lol, I'mma cut you. :)

**Comment by paultag** [comment]
![](https://i.chzbgr.com/maxW500/1385671936/hF787FC83/)

**Comment by fiendish** [comment]
Hehehe

**Comment by fiendish** [comment]
I don't believe in modifying my practice because your tools are shitty. Make your tools suck less, son.

**Comment by paultag** [comment]
![](http://i.imgur.com/QApp7nZ.gif)

**Comment by fiendish** [comment]
I...cannot cope. Must close browser window...
