### ISSUE TITLE
SQL Issue

### ISSUE THREAD

**Issue by Bryghtfalcon** [fiendish/aardwolfclientpackage#203]
![sql error 041014](https://cloud.githubusercontent.com/assets/7257734/2675366/1a8cc58a-c117-11e3-8863-186900cff27f.jpg)
SQL Issue after corporate installed a service pack on my laptop

**Comment by fiendish** [comment]
I believe this means that file writing permissions have changed on your system.
Does anything here help you?
http://www.gammon.com.au/forum/?id=11189

**Comment by Bryghtfalcon** [comment]
Hmm, well, I tried the one fix recommended, If anyone gets this error, set the shortcut to run in Windows XP Service Pack 3 compatibility mode.  Nope.  I have it installed on a flash drive because I am using a work computer. Tried it on 2 different flash drives now.  Darn

**Comment by fiendish** [comment]
Well your problem is happening during the MUSHclient.exe code, not this package. It means your OS is blocking you from making changes to the settings file. Try asking in that thread in the forum.
