### ISSUE TITLE
ssl error on loading 

### ISSUE THREAD

**Issue by saradyne-aard** [fiendish/aardwolfclientpackage#204]
Your username on Aardwolf so I can contact you if more information is
necessary?
Loree

What operating system are you using?
Windows XP

Open the file AardwolfPackageChanges.txt and find the topmost (highest
number) snapshot 'r' number. It should be on the third line of the file and
say something like "r386 snapshot". Paste that line here. If you don't have
this file, you're using a ridiculously old version. Upgrade.
r1792 snapshot

What steps will reproduce the problem?

What is the expected output? What do you see instead? (If applicable,
include copy/paste from output)
Plugin 'aard_package_update_checker' not installed. Attempting to install it...
Run-time error
Plugin: Aardwolf_Package_Update_Checker (called from world: Aardwolf)
Immediate execution
error loading module 'ssl.core' from file '.\ssl.dll':
        The specified procedure could not be found.

stack traceback:
        [C]: at 0x100504e0
        [C]: in function 'require'
        D:\MUSHclient\lua\ssl.lua:9: in main chunk
        [C]: in function 'require'
        D:\MUSHclient\lua\ssl\https.lua:10: in main chunk
        [C]: in function 'require'
        [string "Plugin"]:2: in main chunk
[WARNING] D:\MUSHclient\worlds\plugins\aard_package_update_checker.xml
## Line   39: Error parsing script (Cannot load)

Plugin 'aard_package_update_checker' not installed. Please download and install it.
## It is required for the correct operation of the Aardwolf_New_Connection plugin

Please provide any additional information below.

![output](https://cloud.githubusercontent.com/assets/7338120/2742764/21ed88a8-c709-11e3-8bb8-ac8f3919bea0.JPG)

**Comment by fiendish** [comment]
Hopefully r1793 will fix this for you. Please try downloading now.
https://github.com/fiendish/aardwolfclientpackage/archive/MUSHclient.zip
