### ISSUE TITLE
User Changed Exit getting overridden

### ISSUE THREAD

**Issue by kallemaughl** [fiendish/aardwolfclientpackage#206]
I'm using r1802.

If you use the Change Exit to set the correct room that an exit takes you to, it is overridden by the value reported by gmcp when you reenter the room. I have observed this in two locations:

In Brightsea and Glimmerdim, room 26322 (Dark Laneway), the north exit leads to an ummappable room. The mapper calls the room "nomap_The Glimmerdim Torrent_glimmerdim". I used Change Exit on the north exit of 26322 to set the exit to "nomap_The Glimmerdim Torrent_glimmerdim". The room showed up correctly, as I wanted it to, and the exit no longer showed as unmapped when I used 'mapper unmapped here'. However, when you walk back into 26322, the north exit is set back to 26323 and shows as unmapped.

In Empyrean, Streets of Downfall, room 13959 (A Long and Treacherous Road), the north exit (I believe) changes after you complete the goal. When I go north, I go to room 14073 (Into the Stony Foothills). Just like in the other case, when I set the exit using Change Exit, the room appears as expected. However, when you return to 13959, the mapper changes the exit back to 14041.

-Kallem.

**Comment by fiendish** [comment]
Interesting. I've asked in game whether exits that lead to nomap rooms should get sent via gmcp at all. I'll decide what to do with this after the answer. I think the game just shouldn't send exit destination UIDs for rooms that then return UID -1.

**Comment by fiendish** [comment]
New feature in https://github.com/fiendish/aardwolfclientpackage/commit/b7158b96a4d125403c0428c46f560a7e732e7e52 to flag a room to ignore exit mismatches between what's in the DB and what gets sent by the MUD.
