### ISSUE TITLE
request ASCII map on repop

### ISSUE THREAD

**Issue by mikeride** [fiendish/aardwolfclientpackage#208]
I know you saw the note on ideas board (31691), but just to make the request official, adding the following to the OnPluginBroadcast() function would be great:
      if (text == "comm.repop") then
         SendNoEcho("map")  
      end
It would fit well just before line 494.

Abe

**Comment by fiendish** [comment]
Thanks for the report and code suggestion. Added in c9358ee3133ef0fa53ed5ad3241d7e5c4c01161c
