### ISSUE TITLE
Allow manually setting of norecall/noportal

### ISSUE THREAD

**Issue by ralyn** [fiendish/aardwolfclientpackage#212]
Would like ability to manually set a room that allows recall or portal to norecall/noportal.  Would like to not have mapper try to run to specific rooms that you can recall/portal that are surrounded by norecall/noportal rooms, if that room has a locked door or an aggro.

**Comment by fiendish** [comment]
> Would like to not have mapper try to run to specific rooms that you can recall/portal...if that room has a locked door or an aggro.

It sounds to me like you want to mark a room as "off limits". Is this not already covered by level locking exits into the room?

**Comment by ralyn** [comment]
lockexit doesn't work for exactly what I want here, because there could be a cp/gq/q mob in the room, so I want to be able to go into that room using mapper, just not when I'm trying to get out of the area (using xrt aylor for example).  I can give a specific example of a room that I set this using a buggy workaround if you want.

**Comment by fiendish** [comment]
Examples are always helpful.

**Comment by ralyn** [comment]
Room 10534, in Sanctity with aggro mob king skeleton.  Has a locked door to get into it which is nopass.  It allows portal or recall (I can't remember now).  When I am around that room, say I had a quest in room 10532, and then I use xrt aylor to get out of that area because that room is norecall/noportal.  I don't want mapper to try to go to 10534 in this case because I would have to get a key and kill the aggro to get out.

It's possible to get king skeleton as gq/cp/q mob though, so I don't want to lock the exit into 10534 or else mapper wouldn't be able to get into that room.

**Comment by fiendish** [comment]
I see.
Please test https://raw.githubusercontent.com/fiendish/aardwolfclientpackage/d38931c235d36600756b343a20a222c6782977c8/MUSHclient/worlds/plugins/aard_GMCP_mapper.xml

**Comment by ralyn** [comment]
Works great, exactly what I was looking for.

Had to update to the latest mush version to get rid of errors when I installed that mapper.

**Comment by fiendish** [comment]
Possible. Do you remember what errors?

**Comment by ralyn** [comment]
I kept the old version in case I had an issue with the upgrade:

Run-time error
Plugin: Aardwolf_GMCP_Mapper (called from world: Aardwolf)
Function/Sub: OnPluginBroadcast called by Plugin Aardwolf_GMCP_Mapper
Reason: Executing plugin Aardwolf_GMCP_Mapper sub OnPluginBroadcast
[string "Plugin"]:1248: attempt to index field 'ROOM_COLOUR' (a nil value)
stack traceback:
        [string "Plugin"]:1248: in function 'supplied_get_room'
        ...s\ba046r\Documents\MUSHclient.old.old\lua\aardmapper.lua:226: in function 'get_room'
        ...s\ba046r\Documents\MUSHclient.old.old\lua\aardmapper.lua:813: in function 'draw'
        [string "Plugin"]:2592: in function 'got_gmcp_room'
        [string "Plugin"]:2702: in function <[string "Plugin"]:2691>
Error context in script:
1244 :       load_area_from_database(ourroom.area)
1245 :    end -- not in cache
1246 : 
1247 :    local room = copytable.deep(ourroom)
1248*:    room.bordercolour = mapper.ROOM_COLOUR.colour
1249 :    if areas[room.area] then
1250 :       room.texture = areas[room.area].texture
1251 :       if areas[room.area].color ~= "" then
1252 :          room.bordercolour = areas[room.area].color or mapper.ROOM_COLOUR.colour

**Comment by fiendish** [comment]
Ah. I see. Yeah, the mapper has actually two files. One is called
aardmapper.lua in the lua directory and it contains all the display stuff.
At some point last year I changed around the display configuration options.

**Comment by fiendish** [comment]
Closing. Will be included in next release.
