### ISSUE TITLE
Enable MUSHClient parsing override in AardMUSH

### ISSUE THREAD

**Issue by TheRealGorsk** [fiendish/aardwolfclientpackage#213]
Placing a semicolon at the front of a line overrides normal parsing and sends single semicolons to world verbatim.
I think it'd be cool if some mapper command patterns were preceded by a (?:[;])? to allow MUSHClient's parsing override; thus, eliminating the need to double your semicolons when setting cexits and portals.

Gorsk

**Comment by fiendish** [comment]
This already works.
