### ISSUE TITLE
Info lines don't appear in the comm window unless they're also echoed in the main window

### ISSUE THREAD

**Issue by sethleblanc** [fiendish/aardwolfclientpackage#214]
Commit 0886b04 changed the chat echo plugin to stop evaluating triggers in other plugins, forcing them to trigger on the simulated re-echo of the line rather than the original one. This had the side effect of preventing the comm window from capturing info (and other untagged lines) unless they are also echoed in the main window, which may not always be desired.

As a side note, this change also breaks old plugins that were previously able to trigger on channel lines that were not echoed to the main window. It's still possible to trigger on these with GMCP (incentive to update, I guess?) but thought it was worth mentioning.

**Comment by fiendish** [comment]
> side effect of preventing the comm window from capturing info (and other untagged lines) 

Oops. Try https://github.com/fiendish/aardwolfclientpackage/commit/7f09b5edf5a6a14534409fed9fbb7647bbd24067

> As a side note, this change also breaks old plugins that were previously able to trigger on channel lines that were not echoed to the main window.

The reason for the change is posted here:
http://mushclient.com/forum/bbshowpost.php?bbsubject_id=12790
If you want to bypass the block, you can set your plugin sequence to between -10000 and -5001

**Comment by koalix** [comment]
Well, I tried this with one plugin and it still doesn't work even after i put the sequence to -5001 or -10000. It only worked when I put the tells/gtell to the main window anyway.

**Comment by fiendish** [comment]
Is your plugin calling simulate? Show me the plugin.

**Comment by koalix** [comment]
<muclient>
<plugin
   name="Myrkul_GroupManagement"
   author="Myrkul"
   id="5b4358e3d892a830f8efa8e4"
   language="Lua"
   purpose="Triggers for inviting and leadering people in the Inferno group."
   date_written="2012-10-01 23:48:02"
   requires="4.72"
   version="1.0"
   sequence="-9999"


</plugin>

<triggers>

```
<trigger
    name="invite"
    enabled="y"
    script="invite"
    match="^(?:\{chan ch=gtell\}\(Group\) (.+):|\{tell\}(.+) tells you) 'invite ([A-Za-z]+)(?:(?:,? please)?,? (?:koala|kbear|thoraxis)?)?(?:!|\.| :\))?'$"
    regexp="y"
    sequence="100"
>
</trigger>

<trigger
    name="leader"
    enabled="y"
    script="leader"
    match="^\{chan ch=gtell\}\(Group\) ([^:]+): '(?:leader|promo(?:te)?) me(?:(?:,? please)?,? (?:koala|kbear|thoraxis))?(?:!|\.| :\))?'$"
    regexp="y"
    sequence="100"
>
</trigger>
```

</triggers>

<script>
<![CDATA[
    require "gmcphelper"
    local groupleaders = {"Myrkul", "Antistes"}
    
    function getleader()
        res, gmcparg = CallPlugin("3e7dedbe37e44942dd46d264","gmcpval","group")
        luastmt = "gmcpdata = " .. gmcparg
        assert(loadstring (luastmt or "")) ()
        return gmcpval("leader")
    end
    
    function isgroupleader(player)
        for i, v in ipairs(groupleaders) do
            if v == player then
                return true
            end
        end
        return false
    end
    function invite(name, line, wildcards)
        local player = wildcards[1] .. wildcards[2]
        player = string.match(player, ".+ (%a+)") or player
        if getleader() == "Thoraxis" and isgroupleader(player) then
            Send("group invite " .. (wildcards[3] == "me" and player or wildcards[3]))
        end
    end
    
    function leader(name, line, wildcards)
        local player = wildcards[1]
        player = string.match(player, ".+ (%a+)") or player
        if getleader() == "Thoraxis" and isgroupleader(player) then
            Send("group leader " .. player)
        end
    end
    
]]>
</script>

</muclient>

**Comment by fiendish** [comment]
Ok, looks fixed now. I really appreciate these reports. I didn't realize how fragile the plugin sequence change on chat echo would be.
