### ISSUE TITLE
Suppress map updates requests during mapper goto

### ISSUE THREAD

**Issue by AardCrowley** [fiendish/aardwolfclientpackage#219]
Every time you open a door, the map updates. This is good idea in theory, but creates unnecessary spam when you're trying to reach a destination.

For example:

mapper goto 25754

If you have all the doors mapped with cexits, you wind up opening up 30+ doors to get to that room. As a result, once you've reached your destination, you are spammed with 30+ map update requests.

Perhaps adding an "ignore update request until destination room is reached" clause in the code would work. Personally, I'd like to see the option to toggle update requests on or off as a whole.

Also, any chance you could remove the Note("Requesting map update") from the code? I don't know if it was meant for debugging purposes, but I don't care to be notified that it's requesting map update every time someone opens a door, pops in the room, or otherwise does something to fire the trigger. Thanks!

**Comment by fiendish** [comment]
Lol. You're right of course. I'll add this tonight.

**Comment by fiendish** [comment]
Added in https://github.com/fiendish/aardwolfclientpackage/commit/3f98a9361f10af099fa33f0d31ff66e720cebdb6
