### ISSUE TITLE
mapper portallevel error

### ISSUE THREAD

**Issue by AardCrowley** [fiendish/aardwolfclientpackage#220]
Reach me as Arcidayne, obviously.

Attempted to do: mapper portallevel 27 300 to change the portal level. It kicked back this error:

Run-time error
Plugin: Aardwolf_GMCP_Mapper (called from world: Aardwolf)
Function/Sub: map_portal_level called by alias
Reason: processing alias ""
[string "Plugin"]:737: bad argument #6 to 'format' (no value)
stack traceback:
        [C]: in function 'format'
        [string "Plugin"]:737: in function <[string "Plugin"]:718>
Error context in script:
 733 :    local count = 1
 734 :    local found = false
 735 :    for row in dbnrowsWRAPPER(PORTALS_QUERY) do
 736 :       if count == pnum then
 737*:          query = string.format ([[
 738 :             INSERT OR REPLACE INTO exits (dir, fromuid, touid, level) 
 739 :             VALUES (%s, %s, %s, %s, %s);
 740 :             ]], 
 741 :             fixsql(row.dir),  -- direction (eg. "n")

**Comment by fiendish** [comment]
I mean, of course! What good is an update without introducing a dozen new bugs! :grimacing:
fixed in https://github.com/fiendish/aardwolfclientpackage/commit/261e219fad5c5db233cb8602c73c924b74d306dd
