### ISSUE TITLE
possible issue with Aardwolf_Ascii_Mapper

### ISSUE THREAD

**Issue by mu3r73** [fiendish/aardwolfclientpackage#231]
Hi. I'm running r1845 of aardwolfclientpackage-MUSHclient.zip on Windows 7 64-bit.

I forgot my char idling, and it didn't get disconnected. (To my understanding, this isn't illegal per se, but discouraged.)

I haven't installed other plugins yet, I have no triggers or timers, or anything that could be causing this to happen.

After poking around scripts for a bit, I noticed these newish lines in aard_ASCII_map.xml:

function OnPluginBroadcast (msg, id, name, text)
(...)
      elseif (text == "comm.repop") then
         request_new_map()
(...)

Those seem to keep my char requesting a new map every time the area repops, and hence it was unable to idle out.

**Comment by fiendish** [comment]
Thank you for the report. this will be fixed in the next update. see: 09212230bf8c1555c5be080d921a6a1c8a33c800
