### ISSUE TITLE
beep on page

### ISSUE THREAD

**Issue by mikeride** [fiendish/aardwolfclientpackage#237]
Hey Fiendish,
It came up on the tech channel today that when someone is paged, they are not getting beeped. I know that I haven't received a "termbel" on page in years, so I wrote my GMCP script in tinyfugue to manually beep on receiving a page. I seem to recall you doing some stuff to get page beeps working in the MUSHclient package in the past as well. If you have, it's broken again. If you haven't, please do :-).

I see on 2016-05-20 you made references to it working for all but self-pages.

Abe

**Comment by fiendish** [comment]
![screenshot from 2016-08-22 14-14-32](https://cloud.githubusercontent.com/assets/201996/17866032/f7c41ec6-6872-11e6-8837-1d5dbb8df9a5.png)

**Comment by fiendish** [comment]
Pages do include \07 when sent to you from another player. Pages to self are just echoes, not real pages, though.

**Comment by fiendish** [comment]
Status?

**Comment by mikeride** [comment]
Just to keep updates here, Fiendish came onto the MUD and we worked out a bit further why it works for him but doesn't work for others. The \07 is sent ONLY via GMCP, and is NOT sent via tagged channels. Fiendish's bleeding edge has replaced the tagged-channel portion of the channel plugin with a GMCP-only version now that the functionality for that exists on Aard. The comm log window doesn't process the beep on \07, but if it's echoed to the main window, THAT will proc the beep.

**Comment by fiendish** [comment]
> The comm log window doesn't process the beep on \07, but if it's echoed to the main window, THAT will proc the beep.

I'm looking into a solution for needing to echo.

**Comment by fiendish** [comment]
fixed in 28cf6af6bd973d048f5abae2f66e92182e313811
will be in next release
