### ISSUE TITLE
Text Substitution plugin breaking ANSI

### ISSUE THREAD

**Issue by daagar** [fiendish/aardwolfclientpackage#240]
Attempting to change default ANSI colors within the client (via Game->Configure->ANSI Output...) will 'break' color display within the game. 

Scenario:
* Change the default for bold red to something other than "red" (such as "firebrick")
* In game, 'colorset colors' and 'colorset status' will show all settings that should be the new 'firebrick' color in the default (grey) color (ie., anything with the color code @R)
* Change the default for bold red to any _true_ ANSI color (such as "yellow")
* This will restore functionality (with red being yellow, of course). Obviously, resetting to true red also restores functionality.

Disabling the Text Substitutions plugin fixes the issue.

Tested with client version 1899 and 1900.

**Comment by fiendish** [comment]
Is this fixed for you by replacing worlds/plugins/aardwolf_colors.lua with https://raw.githubusercontent.com/fiendish/aardwolfclientpackage/development/MUSHclient/worlds/plugins/aardwolf_colors.lua
?

**Comment by fiendish** [comment]
I believe this was fixed in 65ddfef26914e8dab44336fc7664f9e6036567da
