### ISSUE TITLE
Gmcp_Mapper displaying fully black or partially black output

### ISSUE THREAD

**Issue by JSLowery** [fiendish/aardwolfclientpackage#244]
The Gmcp Mapper appears to have a bug where it displays either fully black with its boarder, or partially black where it will show the room name and about 1/8th of the next line.

Just for note, it is not another window on top of it, moved it around and resized it, tried right clicking and bring to front. 
Also, the popups still work when hovering over parts of it. Clicking inside it still runs to wherever you clicked if you get lucky and hit a box. 
All mapper functions appear to still work, but the display is just gone after a while. I cannot seem to reliably replicate the issue, it just happens after moving around for a while with no error.

I am using r1900 under wine 2.4 (Staging) but it happend also when using wine 1.6.

**Comment by fiendish** [comment]
I believe that this is a latent MUSHclient bug that a few people have reported in different miniwindows over time but noone has ever been able to reliably reproduce. How many times has it happened?

**Comment by JSLowery** [comment]
This happens every time I am logged in. I have not been able to figure out why it is happening though.

**Comment by fiendish** [comment]
EVERY TIME! I know you probably don't think so, but that's awesome. Nobody has ever been able to see that kind of regularity with this. It gives me some small hope of finally being able to track it down. I'll try to catch you on aard to see if maybe I can pass you some modified versions of the plugin to find out more about what's going on.

**Comment by fiendish** [comment]
I think we managed to provide enough information upstream and this has now been fixed in MUSHclient. (And there was much rejoicing)
