### ISSUE TITLE
Run-time error in mapper

### ISSUE THREAD

**Issue by metria** [fiendish/aardwolfclientpackage#248]
I received this error while running.

Run-time error
Plugin: Aardwolf_GMCP_Mapper (called from world: Aardwolf)
Function/Sub: OnPluginBroadcast called by Plugin Aardwolf_GMCP_Mapper
Reason: Executing plugin Aardwolf_GMCP_Mapper sub OnPluginBroadcast
[string "Plugin: Aardwolf_GMCP_Mapper"]:2802: cannot commit - no transaction is active

CODE: 1
QUERY: COMMIT;

stack traceback:
        [C]: in function 'error'
        [string "Plugin: Aardwolf_GMCP_Mapper"]:146: in function 'dbcheck'
        [string "Plugin: Aardwolf_GMCP_Mapper"]:134: in function 'dbCheckExecute'
        [string "Plugin: Aardwolf_GMCP_Mapper"]:2802: in function 'got_gmcp_room'
        [string "Plugin: Aardwolf_GMCP_Mapper"]:2920: in function <[string "Plugin: Aardwolf_GMCP_Mapper"]:2908>

You are currently using Aardwolf MUSHclient Package version: r1927

Details about this room:
+---------------------------+
Name: Wooden pews
ID: 47589
Area: aardington
Terrain: temple
Info: 
Notes: 
Flags:
Exits: 
"w"="47588"
"e"="47591"
"s"="47592"
"n"="47590"
Exit locks: 
"w"="0"
"e"="0"
"s"="0"
"n"="0"
Ignore exits mismatch: nil
+---------------------------+

**Comment by fiendish** [comment]
Do you remember where you were running from and to?

**Comment by metria** [comment]
Is this the issue you fixed in r1930?

**Comment by fiendish** [comment]
Fixed by 60de08c48b0b2bcaece6cf1294713583ecef7ece
