### ISSUE TITLE
any interest in a windows installer that supports client upgrade?

### ISSUE THREAD

**Issue by ghost** [fiendish/aardwolfclientpackage#249]
I suspect the client upgrade instructions are a bit much for some people, all of those steps/choices could be managed with options in an installer.   Odds are if my wife and I get into playing, I'll write an installer anyway using inno-setup so I don't have to walk her through it every time.

If there's interest, and the build chain for the client includes a windows machine.. I'd be happy to contribute an inno-setup script and any build files necessary.

**Comment by fiendish** [comment]
I did this a while ago. https://fiendish.github.io/aardwolfclientpackage/

**Comment by ghost** [comment]
Didn't see any mention of that on the client download page, perhaps I just missed it?

**Comment by fiendish** [comment]
aardwolf.com stays behind my development cycle by a fair bit because of the
odds of introducing bugs with new features. I have a few more bugs that I
want to fix before asking lasher to post a new build there.

**Comment by ghost** [comment]
Thanks for the details, and the link to the installer..
