### ISSUE TITLE
Notepad and recall window

### ISSUE THREAD

**Issue by JSLowery** [fiendish/aardwolfclientpackage#250]
The information formerly stored in the notepad and recall windows is now being translated to some other form than ASCI or UNICODE. My notepad is now in what appears to be Chinese. Also, as of 1-16-18 a few other people have complained of this. 

According to Edit(player):
[16 Jan 08:23:26] Edit Tech: anything in the recall window or notepad windows gets translated to stuff like this: ???????4????????????????????????????????????????????????4???????????????????????????????4??????????????
[16 Jan 08:26:01] Edit Tech: the notepad windows eventually go back to normal but initially it's question marks that the screen reader identifies as being in different fonts.
[16 Jan 08:26:25] Edit Tech: but the recall window is always the question marks

I can attest that the information in my notepad window is now:
Gone actually as of last check but it was 5 Chinese characters when I started writing this.

**Comment by JSLowery** [comment]
This happens in the newest update r1955. Both Edit and myself are running under windows. I am using win7 and not sure which windows Edit is using.

**Comment by JSLowery** [comment]
apparently if I keep going to my notepad it randomly changes which encoding it is using because now it is:
整档 כ 

Instead of just blank or the previous Chinese characters.

**Comment by JSLowery** [comment]
Oh, and on exit of the notepad it seems to give me a random file name..
I have recieved Ardwolf_health_bars, d. these are the filenames that it is asking me to save when I try to close the window.

**Comment by fiendish** [comment]
Can you give me a series of interaction steps that reproduce this from a fresh run of MUSHclient.

**Comment by JSLowery** [comment]
The steps to reproduce this are:
click Edit  goto notepad.

**Comment by nickgammon** [comment]
Can you please download the latest build from here:

https://github.com/nickgammon/mushclient/releases/download/latest_commit/MUSHclient.exe

Replace the file MUSHclient.exe in your Aardwolf release directory by the file above (better rename the original in case things get worse).

Then try again.

This implements [this commit](https://github.com/nickgammon/mushclient/commit/ed1aa5d2e346be96c1f1fbb04971c4c8eba225f9) which hopefully fixes the problem.

**Comment by JSLowery** [comment]
This file appears to function as intended.
