### ISSUE TITLE
Get Broadcast for mapper goto cancel.

### ISSUE THREAD

**Issue by droslean** [fiendish/aardwolfclientpackage#263]
I am not sure if this is already implemented. But it would be nice to have it.

While "running", there should be a broadcast to wait for something to get, to cancel the speedwalk

**Comment by fiendish** [comment]
I don't understand what you're asking for. Can you explain in more detail?

**Comment by fiendish** [comment]
?

**Comment by droslean** [comment]
Well it seems that is no possible to cancel speedwalk because the run command had already sent to the server.

**Comment by fiendish** [comment]
I still don't understand the issue.
