### ISSUE TITLE
Mushclient repeated crashes.

### ISSUE THREAD

**Issue by JSLowery** [fiendish/aardwolfclientpackage#264]
So my client is repeatedly crashing. I can't seem to pin down the 'when' of it because it seems random. It will crash when I let it idle, or when moving rooms, and when just sitting in clan hall chatting. I tried debugging it in visual studio, I have screen shots of it and a screen shot of the 'trace' that is built in to mushclient during a crash.
OS: Windows 7
Memory usage(at time of crash): 111,682K
I wish I had more information about this for you, but I don't.
![debug](https://user-images.githubusercontent.com/5751490/39663484-37685fa2-5042-11e8-9c42-b5e753182113.png)
![trace](https://user-images.githubusercontent.com/5751490/39663485-3775707a-5042-11e8-8af1-c2a5fff07804.png)

**Comment by fiendish** [comment]
Version?

**Comment by JSLowery** [comment]
was r1955, updated to the newest 1993 and it just crashes on start up..

**Comment by fiendish** [comment]
Is your computer entirely up to date with OS updates?

**Comment by JSLowery** [comment]
Probably not seeing as I turned off windows update somewhere around 2013. I started a new client folder and swapped the .mcl file, script file, and such. Seems to be stable so far. I will update you if this changes.

**Comment by JSLowery** [comment]
So it appears even the new folder won't load up now. It dies on trying to install the aard theme controller.
When I attempt to manually add the line to the .mcl it just breaks.
So it appears that the Omit_Blank_lines.xml was the culprit for the breaking on start..

**Comment by JSLowery** [comment]
So even making a mush trigger to catch ^$ and omit it from output crashes the client eventually. I am guessing it is interacting with something strangely since at least r1955, most likely before that because for years it didn't happen.

**Comment by fiendish** [comment]
So like...any chance you might turn windows update back on just to rule out the possibility of something that might have been fixed in the OS since 2013?

**Comment by JSLowery** [comment]
I don't really feel comfortable turning it back on to be honest. This is an old partition that I only had to revive due to work. I only keep it alive because I work from home a lot. I don't really trust microsoft enough to enable their updater..

**Comment by JSLowery** [comment]
I will log into my linix partition later and do some testing to see if it still happens under an updated linux environment.

**Comment by fiendish** [comment]
You trust Microsoft enough to attach their unpatched OS to the internet, but you don't trust them enough to patch known bugs and vulnerabilities that have accumulated since 2013?

**Comment by JSLowery** [comment]
So I  did do the update, then fixed what it broke. The issue seems to be any trigger that matches ^$ local or in a plugin and on all the time or turned on and off when needed. For some reason the newer versions of mush just don't like this trigger.
An addendum, it is still crashing, albeit much less frequently.

**Comment by fiendish** [comment]
Related to this? https://mushclient.com/forum/?id=14255

**Comment by JSLowery** [comment]
It might be related, but not the cause. I am not using that plugin anymore and still suffer crashes.

**Comment by JSLowery** [comment]
What more information can I give you? I have the errored out program open in VS. I don't know VS very well so I am not sure how to debug this accurately.

**Comment by fiendish** [comment]
Well step 1 is to try downloading r1994 which should fix that bug.  Would you be willing to send me a zipped copy of your whole MUSHclient folder to inspect?

**Comment by JSLowery** [comment]
what email would you like it sent to?

**Comment by fiendish** [comment]
'finger fiendish' on aardwolf

**Comment by JSLowery** [comment]
The r1994 fixed my bug completely. I haven't had a crash since I installed it.

**Comment by JSLowery** [comment]
So I got on my computer today after being absent since last night(the client was on the whole time) and it failed out at the same place as last time. See the VS debug output for placement.
I had really thought it was completely fixed. At least it has slowed down from once an hour or so to every six or so days.

**Comment by fiendish** [comment]
I don't know what I can do about this without more information about the cause. Since you have visual studio, you could try loading MUSHclient_2015.sln from https://github.com/nickgammon/mushclient and seeing if you can get a proper stack trace with function calls in it.

**Comment by fiendish** [comment]
You should also try reporting on the mushclient.com forum if the issue is still happening.
