### ISSUE TITLE
storeFromOutside echo option

### ISSUE THREAD

**Issue by mikeride** [fiendish/aardwolfclientpackage#266]
It would be great in storeFromOutside were an option in the non-channel capture settings, so that you could have a tab for those. This enhancement request came out because of tech post 7676.

**Comment by fiendish** [comment]
Dos the second argument on storeFromOutside satisfy the scenario?  https://github.com/fiendish/aardwolfclientpackage/blob/720c61e4bf1faf4522e36feb021c5746a76679ee/MUSHclient/worlds/plugins/aard_channels_fiendish.xml#L728

**Comment by fiendish** [comment]
I think the answer is probably yes. If not I'll reopen.
