### ISSUE TITLE
aard_health_bars_gmcp.xml doesn't honor disable on relaunch

### ISSUE THREAD

**Issue by mikeride** [fiendish/aardwolfclientpackage#275]
It's missing your usual code block:
   -- if disabled last time, stay disabled
   if GetVariable ("enabled") == "false" then
      ColourNote ("yellow", "", "Warning: Plugin " .. GetPluginName ().. " is currently disabled.")
      check (EnablePlugin(GetPluginID (), false))
      return
   end -- they didn't enable us last time

**Comment by fiendish** [comment]
Yeah. I decided that I don't like the premise of carrying over disable. If someone wants a plugin persistently disabled, they can just remove the plugin.
