### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by mikeride** [fiendish/aardwolfclientpackage#277]
In relation to my "slight command ambiguity" post, it could be helpful to have a command which would purge all cexits in the current (or named) area. As it is right now, you can:
1) purge exits in the current room
2) purge exits in the entire database
3) purge the entire area and re-explore
One use-case scenario would be someone who had done kingsholm goal, and made "next" cexits, but then creates and alt, recreates, gets nuked.

**Comment by fiendish** [comment]
I'd accept a pull request for adding an optional area keyword to either delete or purge cexits, but I'm fine with people needing to re-explore the area until then.
