### ISSUE TITLE
Aard Prompt Fixer - turns off prompt occasionally

### ISSUE THREAD

**Issue by aardbluefeather** [fiendish/aardwolfclientpackage#285]
aard_prompt_fixer.xml plugin can turn off prompt under certain conditions that happen regularly in Winds epic... In current state, prompt checking occurs when:
- char.status broadcast is received
- char.status.state is either 3 or 8

after which fixup function is called:
1. current prompt state (on or off) is checked and saved in var
2. prompt is set to off
3. checks are made to determine if it needs to be fixed
4. prompt is set to whatever was saved in step 1 var

Certain conditions can trigger two or more consecutive char.status broadcasts (happens regularly during winds epic run, possibly in some other situations), that cause fixup function to misread step 1 - setting prompt state to off.

Fix could include changing the trigger conditions to "char.base" broadcast, which happens on entering aard (so, only once per session), or by adding a timer so that it doesn't trigger as often.

To quickly replicate bug, type "echo Prompt set to: something.", hit enter, hit arrow up, hit enter, repeat few times.

**Comment by fiendish** [comment]
You're making me cry. (Thanks for the thorough report though.)

**Comment by fiendish** [comment]
Please try r2051

**Comment by aardbluefeather** [comment]
So, I'm sorry to keep bumping into these errors, but I've bumped into another one - this time in Aardwolf_Ascii_Mapper, function request_new_map - it acts the same way - when someone spam-opens the doors, again the stored prompt state gets mistakenly overwritten. It happens regularly in winds epic, there is a part where 4 doors are opened with alias.

The prompt fixer seems to be fixed tho. :)

Oh and, thanks a bunch for this wonderful package, it's really a delight to play aard with it! :)

**Comment by fiendish** [comment]
Thanks so much for these reports.
Please replace your prompt fixer and ascii map plugins with these two files and let me know if the issues continue or return or manifest in a new way.

https://raw.githubusercontent.com/fiendish/aardwolfclientpackage/development/MUSHclient/worlds/plugins/aard_ASCII_map.xml

https://raw.githubusercontent.com/fiendish/aardwolfclientpackage/development/MUSHclient/worlds/plugins/aard_prompt_fixer.xml

**Comment by aardbluefeather** [comment]
Well, did a few winds runs - it would seem everything is fixed now. :) Thanks a bunch!

**Comment by fiendish** [comment]
Yaaaay.
