### ISSUE TITLE
Add return values for aardmapper.lua functions

### ISSUE THREAD

**Issue by tim-chaplin** [fiendish/aardwolfclientpackage#287]
My use case is that I want to do stuff in response to the mapper failing to find a path to my destination room (usually this happens when there's a maze in the way, so I'd like to automatically walk to the beginning of the current area's maze).

My first thought was to add a trigger on the error message (e.g. "There was 1 match which I could not find a path to within 300 rooms") but it doesn't seem possible to do this in MUSHclient.

The next best option would be if functions like mapper.gotoNextResult() returned an indication of success/failure so I could call that function directly and check the result.

**Comment by tim-chaplin** [comment]
After working on a different problem I realize this suggestion was based on a wrong assumption - I thought that the "mapper" object used in aard_GMCP_mapper.xml was just a global module that I could call from my own plugins. But it seems like it's actually a private object with its own state, so trying to call it without setting up all that state doesn't work.

So, this suggestion as-written is probably impractical, but I'm hoping you'll still have an idea for how to solve my use case.

**Comment by fiendish** [comment]
I don't understand the details of automatically walking to the beginning of the maze. If there's no path, how will it know where to take you?

**Comment by tim-chaplin** [comment]
Related to my pull request - if you query the db for maze rooms in the current area and disable the quick path setting on mapper.find, it only returns rooms that are reachable. Usually there's only one, namely the maze entrance (or exit depending on which side you're on).

I don't think it's reliable enough to walk there automatically, but it's convenient to pop up the list of rooms so I can potentially just click once to get there

**Comment by fiendish** [comment]
Ok, I understand now. Is it safe to close this in favor of your PR?

**Comment by tim-chaplin** [comment]
Sure.
