### ISSUE TITLE
Anyone wanted to do a Linux port of MUSH?

### ISSUE THREAD

**Issue by icedwater** [fiendish/aardwolfclientpackage#295]
Just curious if it would be a good idea.

Actually, no, it's terrible. But if more people could share in the terribleness, it would be slightly less terrible.

**Comment by koalix** [comment]
It depends. According to what I *SEE*, the client right now is too dependable on windows components to be easy to port. Probably the entire GUI needs to be redone for a port exist.

The backend it's easy to port, and I see even an easy port for a text-based client (of course, without the widgets. They can be done on text mode, but it is boring to work with curses and similar text frameworks).

The point here, to invest time in a project like this is: how many people would really use mush on Unix? There are enough players to consider a major overhaul?

Koala

**Comment by fiendish** [comment]
I would love to see a natively cross-platform client that copies MUSHclient's scripting API, but this isn't really the right place for this discussion.

And doing this would be a very large undertaking. You'd have to re-implement basically everything. And MUSHclient works quite well in Wine on Linux and macOS.
