### ISSUE TITLE
r2141 no longer allows inv filter game command to work

### ISSUE THREAD

**Issue by davidcw6** [fiendish/aardwolfclientpackage#298]
Due to the alias change in https://github.com/fiendish/aardwolfclientpackage/commit/e453f85b42fc425965f217ddcfd078151e614f85, users on version 2141 or newer are unable to use the in game command "inv filter <option> as doing so redirects to inv data.

Prior to the change in 2141 the command worked.

**Comment by fiendish** [comment]
Oops. You're correct. It was wrong to change handling of the inv command in that commit.

**Comment by fiendish** [comment]
Try the new snapshot.

**Comment by davidcw6** [comment]
confirmed fixed

**Comment by fiendish** [comment]
Thanks for the report!
