### ISSUE TITLE
GMCP_send in gmcp_handler is broken.

### ISSUE THREAD

**Issue by AardCrowley** [fiendish/aardwolfclientpackage#300]
\\\CallPlugin("3e7dedbe37e44942dd46d264", "GMCP_send", "request char") used to be able to pull data for "char" request (same as protocol gmcp sendchar), but somewhere along the way, it broke. It returns nothing.

**Comment by AardCrowley** [comment]
Turns out you changed it to GMCP_Alias instead. Never mind.

**Comment by fiendish** [comment]
lol. Trying to see if I'm still alive?

**Comment by AardCrowley** [comment]
Haha, well, it WAS a legit question since it broke one of my plugins, then I decided to check the code to see what changed. :P Glad you're still alive, as it were!
