### ISSUE TITLE
'closehelp' alias not functioning

### ISSUE THREAD

**Issue by ArijanJ** [fiendish/aardwolfclientpackage#304]
The alias 'closehelp' does not seem to be functioning for me. It gives no output at all. I tried debugging it manually however `my_window` turns out to be nil. 

![image](https://user-images.githubusercontent.com/56356662/166257729-5e4ef4f9-4e11-4d11-99bd-c5bd3d249668.png)
![image](https://user-images.githubusercontent.com/56356662/166257746-ab3e11bd-2167-4cec-b0db-50fe31ca30a3.png)

These attempts may have been completely futile since I have very little idea of how MUSHclient interacts with its scripts.

**Comment by fiendish** [comment]
this should be fixed now in r2216. thanks for the report!
