### ISSUE TITLE
GMCP Visual Mapper rendering bug

### ISSUE THREAD

**Issue by nohbdy** [fiendish/aardwolfclientpackage#307]
Noticed the mapper was incorrectly rendering the map in this area (tilule).  Client version is r2220.  There are no custom exits in any of the three rooms pictured.  The room farthest west in the hallway (gmcp id 39800) also renders similarly to the first image (although with the other room highlighted, naturally).  If you need them the 'Map configuration settings' are depth 300, font consolas 9, area textures off, show room id on, show area exits on, room size 12.

Upon further investigation, the same issue occured on the 'first floor' of tilule as well.

**The issue also resolved itself with a 'reinstall' of the Aardwolf_GMCP_Mapper plugin.**

Unsure what triggered this, was just campaigning.

![aardwolf_mapper_bug](https://user-images.githubusercontent.com/181182/177989526-8e94d589-b10e-4c05-9251-41e27625127e.png)
![aardwolf_mapper_bug2](https://user-images.githubusercontent.com/181182/177989528-09eb8281-cc5a-4836-a007-41fb262ea70f.png)
![aardwolf_mapper_bug3](https://user-images.githubusercontent.com/181182/177989529-56d9d22b-1a93-4e65-8e29-7df3b4464384.png)

**Comment by fiendish** [comment]
Weird. The fact that it resolved itself after reloading the plugin suggests some kind of failure to load the room information from the database file, but without some kind of visible error message I don't think I can do much yet other than just hope it doesn't happen again.
