### ISSUE TITLE
Prompt fixer & p data

### ISSUE THREAD

**Issue by Tymme** [fiendish/aardwolfclientpackage#308]
```
prompt %K@GH-%p @CM-%P @M%vmv @x150AL:%a @WNL:%X QT:%q%d%c@w
Prompt set to %KH-%p M-%P %vmv AL:%a NL:%X QT:%q%d%c

The Aardwolf MUSHclient Package is adjusting your game prompt to end in '%c'.
This is necessary for triggers to work properly.
If you've encountered script errors, try restarting MUSHclient now to let scripts reinitialize.
prompt %K@GH-%p @CM-%P @M%vmv @x150AL:%a @WNL:%X QT:%q%d%c
```

Copying from 'p data' includes the @w (not sure if it is added by the MUD with the prompt command or not).  Could prompt fixer detect %c@w and not try to correct?  Or a MUD-size change to not paste/append the @w?

**Comment by fiendish** [comment]
It's doing the right thing but giving an unhelpful message. (If you include "@w" at the end of your prompt input, Aardwolf does something bad by adding another space and then another "@w", so your "blahblah%c@w" turns into "blahblah%c@w @w". The plugin therefore removes your "@w" at the end to produce the p data you actually want.)
In the next update this should cause a hopefully less confusing message.
