### ISSUE TITLE
keyring data not available when sleeping (inventory-serials)

### ISSUE THREAD

**Issue by jedineeper** [fiendish/aardwolfclientpackage#312]
If you call "inventory" whilst sleeping there is a failed attempt to call `keyring data` due to the characters state. This results in the keyring returning empty in the display.

There is a blocked_by_status call in the function [here](https://github.com/fiendish/aardwolfclientpackage/blob/MUSHclient/MUSHclient/worlds/plugins/aard_inventory_serials.xml#L36-L48) but it allows it to pass whilst sleeping despite it not being possible ingame? (state 9 if I read the code correctly?) 

Not sure if this is something that should be fixed here or posted to bugs to ask for keyring data to be permitted whilst asleep?

Thanks,
Neeper
```
<prompt> i

You entered: keyring data
You dream about being able to keyring.

You entered: invdata
You are carrying:
*snipped for brevity*
( 2) (K)(M)(G)(H) a Bag of Aardwolf  [123,435]  (201)
( 0) ** Items on Keyring (0 unique) **

<prompt>
```

version: 2252

**Comment by fiendish** [comment]
lol, nice catch

**Comment by fiendish** [comment]
IMO this is a game bug. Keyring and vault data should be accessible while sleeping the same way that invdata is. Not sure if I want to work around it or just wait for Lasher to address it.

**Comment by fiendish** [comment]
May as well, I guess.
Workaround added in https://github.com/fiendish/aardwolfclientpackage/commit/5c2928554d579854fc000be1e14bc47b224c93f8

This should do the right thing after it gets fixed in the game too.
