### ISSUE TITLE
chat log rotation

### ISSUE THREAD

**Issue by jedineeper** [fiendish/aardwolfclientpackage#313]
the chat window plugin logs all the chat text to `logs/AardwolfChatLog.txt` whilst its not a lot of data, having some form of rotation or date-split done automatically would be super useful I feel for finding stuff in the past without running into file-open handles.

**Comment by fiendish** [comment]
there's already an option to split after a certain file size, so I'm going to close this issue. But if you're talking about something else feel free to reopen it.

![image](https://user-images.githubusercontent.com/201996/227440299-94bcf497-7881-4c79-b371-4f222ade8309.png)
