### ISSUE TITLE
feature request: additional timestamp formats for Communication Log

### ISSUE THREAD

**Issue by danj2k** [fiendish/aardwolfclientpackage#316]
None of the existing timestamp formats available for selection in the Communication Log right-click menu include the year. While this is typically not important in the immediate context of the MUD, I've frequently copied lines from the communication log to my own notes for reference purposes, and it would be useful if these also contained the year.

I'd therefore like to suggest the addition of a timestamp option with an ISO format date stamp, for example `2023-03-04 12:33:21`.

It looks like the code for this is in `aard_channels_fiendish.xml` in the function `extend_rightclick_menu` and I believe adding something like the following should accomplish this request:

```
      {
         ((date_format == "[%Y-%m-%d %H:%M:%S] ") and "+" or "").."2023-08-30 13:20:12",
         function()
            date_format = "[%Y-%m-%d %H:%M:%S] "
            ColourNote("yellow", "", "Timestamps in communication window ENABLED using format like '2023-08-30 13:20:12'.")
            SaveState()
         end
      },
```

**Comment by fiendish** [comment]
thanks!
added in https://github.com/fiendish/aardwolfclientpackage/commit/79e1d181776d5c926b862223ab3e7a1877e9edf2
will be in the next release
