### ISSUE TITLE
Cannot Load VI Review Buffers Plugin

### ISSUE THREAD

**Issue by AreiaAard** [fiendish/aardwolfclientpackage#321]
Looks like Mush is unhappy about a recent change to the VI Review Buffers plugin name...

> [WARNING] ...\MushClient\worlds\plugins\aard_vi_review_buffers.xml
Line   17: Plugin name cannot be > 32 characters (Cannot load)

**Comment by fiendish** [comment]
fixed in the next release. thank you!
