### ISSUE TITLE
msvcr120.dll missing

### ISSUE THREAD

**Issue by lightsrage** [fiendish/aardwolfclientpackage#328]
I tried to run mushclient.exe from the aardmush directory, and I got a code unale to exicute, msvcr120.dll is missing. ok button hit ok tried to troubleshoot  things repairing all my vb redisstributibles.   that did not help tried running other portable mush clients on the system,  those worked fine. and aard worked fine till i updated.  I then tried toppying things over to see what I could do to make it work, no luck reinstalling the aar updated package did not help. I am unsure what to do at this point.

**Comment by fiendish** [comment]
What version of Windows do you have? Did this happen just after a system update?

**Comment by fiendish** [comment]
Ah. I think I found the cause. There was a change in the LuaJIT build script that I missed. I think I've fixed it now.
