### ISSUE TITLE
Aardwolf_Chat_Capture_Miniwindow - exceptions for socials

### ISSUE THREAD

**Issue by piotrpatrzylas** [fiendish/aardwolfclientpackage#337]
Sometimes  miniwindow captures wrong mud output.

It is encoded as:  match="^\*\S(?!.*[\]\*] *$).+$"

Captures wrong output as socials - examples are transcendcence first room typing list or rooms in quarry (quarry floor - desc).

Temporary solution - chance match to:
   match="^\*\S(?!(.*[\]\*] *$)|(RACK\* of a whip\. Giant slabs of unidentified rocks are being hewn from the)|(urchase using 'buy <keywords without spaces>')).+$"

**Comment by fiendish** [comment]
duplicate of #326
